[package]
name = "surpass"
version = "0.1.0"
authors = ["dtiselice <dtiselice@google.com>"]
edition = "2018"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
rayon = "1.2.1"
rustc-hash = "1.0.1"

[dev-dependencies]
rand = "0.7.3"
