[package]
name = "mold"
version = "0.1.0"
authors = ["dtiselice <dtiselice@google.com>"]
edition = "2018"

[dependencies]
rustc-hash = "1.0.1"
surpass = { path = "../surpass" }

[dev-dependencies]
argh = "0.1.3"
image = "0.22"
piston_window = "0.105.0"
rand = "0.7"
svg = "0.5"
svgtypes = "0.4"

[profile.release]
#lto = "fat"
