[package]
name = "rive"
version = "0.1.0"
authors = ["Dragoș Tiselice <dragostiselice@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flagset = "0.3"
once_cell = "1.5"
smallvec = "1.6"
